version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: eq_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: earthquakes
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
